### ISSUE TITLE
abaqus build in mpl

### ISSUE THREAD

**Issue by X-G** [youngung/mpl-lib#1]
Hi @youngung , 

I found that you are a python and abaqus user as well. 
It's very convenient to use mpl to plot figures directly in abaqus' python environment, because it avoid export odb data to files.
I found a method to put mpl module  in abaqus' python environment on Windows platform, find the method on github: [matplotlib-4-abaqus](https://github.com/Solid-Mechanics/matplotlib-4-abaqus).
But this method has some issue on Linux platform [Solid-Mechanics/matplotlib-4-abaqus#2](https://github.com/Solid-Mechanics/matplotlib-4-abaqus/issues/2) and still not been solved.
If you are interested in using mpl in abaqus, you can check it out and maybe will find out the solution.

This issue doesn't really relate to your repo, please close it at any time.

cheers.

**Comment by youngung** [comment]
You might want to consider adding your local python site-package-path to $PATH on Abaqus Python.
In the Abaqus Python IDLE, you can add the Python's site-package path to $PATH such as below:

```
import os
path_site_packages='/home/younguj/anaconda2/lib/python2.7/site-packages/'
os.sys.path.append(path_site_packages)
```

Note that I'm using anaconda2 and you should change the path_site_packages according to your local Python configuration.

According to my experience, the above method enabled me to use my own Python modules including a few third party packages in Linux/Mac.
Of course, you can save the above to a separate module and load in Abaqus.

I don't know if this would resolve your issue - I haven't even read it yet...
But I’ll be very much interested in resolving your issue.

Youngung

**Comment by X-G** [comment]
Thanks @youngung , I will try you method later today when I can access my ubuntu machine.
